export const State = {
    isScanning: false,
    progress: 0,
    tokens: 0,
    cost: 0,
    securityScore: 100,
    uxScore: 100,
    activePlugins: ['github-sync', 'cost-optimizer'],
    logs: [],
    securityAlerts: [],
    bridgeStatus: 'OFFLINE',
    telemetry: { cpu: 0, memory: 0 },
    recommendations: [],
    isTaskRunning: false,
    devopsLogs: [],
    authKey: "",
    geminiKey: "",
    remoteModel: "gemini-2.5-flash",
    ollamaUrl: "http://localhost:11434/api/generate",
    localModel: "llama3:latest",
    allowRemoteCode: false,
    codebaseIndex: {},
    lastConnected: null,
    connectionAttempts: 0,
    boardFindings: [],
    boardHistory: []
};
